name: Build against eic-shell

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          # install this repo
          CC=gcc CXX=g++ cmake -B build -S .
          cmake --build build -- -j 2 install
    - uses: actions/upload-artifact@v3
      with:
        name: build-gcc-eic-shell
        path: |
          .
          !src/
          !apt_cache/
        if-no-files-found: error

  build-clang:
    runs-on: ubuntu-latest
    needs:
    - build-gcc
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          # install this repo
          CC=clang CXX=clang++ cmake -B build -S .
          cmake --build build -- -j 2 install
    - uses: actions/upload-artifact@v3
      with:
        name: build-clang-eic-shell
        path: |
          .
          !src/
          !apt_cache/
        if-no-files-found: error

  ddsim:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        detector_config: [arches, brycecanyon]
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          ddsim --compactFile ${DETECTOR_PATH}/${DETECTOR}_${{ matrix.detector_config }}.xml -G --gun.particle "pi-" --gun.momentumMin "1*GeV" --gun.momentumMax "20*GeV" --gun.distribution "uniform" -N 100 --outputFile sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root
    - uses: actions/upload-artifact@v3
      with:
        name: sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root
        path: sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root
        if-no-files-found: error  

  eicrecon-gcc:
    runs-on: ubuntu-latest
    needs:
    - build-gcc
    - ddsim
    strategy:
      matrix:
        detector_config: [arches, brycecanyon]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-gcc-eic-shell
    - uses: actions/download-artifact@v3
      with:
        name: sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          export DETECTOR_CONFIG=${DETECTOR}_${{ matrix.detector_config }}
          export JANA_PLUGIN_PATH=$PWD/lib/EICrecon/plugins${JANA_PLUGIN_PATH:+:${JANA_PLUGIN_PATH}}
          chmod a+x bin/*
          $PWD/bin/eicrecon -Ppodio:output_file=rec_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4eic.root sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root -Pplugins=dump_flags -Pdump_flags:json=${{ matrix.detector_config }}_flags.json
    - uses: actions/upload-artifact@v3
      with:
        name: eicrecon_rec_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4eic.root
        path: rec_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4eic.root
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ matrix.detector_config }}_flags.json
        if-no-files-found: error

  run_eicrecon_reco_flags-gcc:
    runs-on: ubuntu-latest
    needs:
    - build-gcc
    - ddsim
    strategy:
      matrix:
        detector_config: [arches, brycecanyon]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-gcc-eic-shell
    - uses: actions/download-artifact@v3
      with:
        name: sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          export DETECTOR_CONFIG=${DETECTOR}_${{ matrix.detector_config }}
          export JANA_PLUGIN_PATH=$PWD/lib/EICrecon/plugins${JANA_PLUGIN_PATH:+:${JANA_PLUGIN_PATH}}
          chmod a+x bin/*
          $PWD/bin/run_eicrecon_reco_flags.py sim_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4hep.root rec_pi_1GeV_20GeV_${{ matrix.detector_config }} -Pdump_flags:json=${{ matrix.detector_config }}_all_good_flags.json
    - uses: actions/upload-artifact@v3
      with:
        name: run_eicrecon_reco_flags_rec_pi_1GeV_20GeV_${{ matrix.detector_config }}.edm4eic.root
        path: rec_pi_1GeV_20GeV_${{ matrix.detector_config }}.tree.edm4eic.root
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ matrix.detector_config }}_all_good_flags.json
        if-no-files-found: error

generate-docs:
  runs-on: ubuntu-latest
  needs:
    - run_eicrecon_reco_flags-gcc
    - eicrecon-gcc
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: arches_all_good_flags.json
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          ls -ll
